version: "3.9"
services:
  postgres:
<<<<<<< HEAD
    image: postgres:12-alpine
=======
    image: postgres:14-alpine
>>>>>>> d4d0e58 (refactor)
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
<<<<<<< HEAD
=======
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
>>>>>>> d4d0e58 (refactor)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
<<<<<<< HEAD
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
=======
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
volumes:
  data-volume:
>>>>>>> d4d0e58 (refactor)
